name: Build and Release Binaries

on:
  release:
    types:
      - published

jobs:
  binaries:
    uses: pablozaiden/installer/.github/workflows/reusable-binary-release.yml@126f52a743c46db69baeccfcd6350b52d2569c2a #hot fix
    permissions:
      contents: write
    with:
      prebuild_command: bun run build
      binaries: |
        [
          {
            "name": "link-cli",
            "asset_prefix": "link-cli",
            "build_command": "bun run build-binary.ts --target=$BUN_TARGET --outfile=dist/$ASSET_NAME",
            "output_path": "dist/$ASSET_NAME"
          }
        ]
